name: Pull File from Another Repository on Push
env:
  SOURCE_REPO: https://github.com/lwcorp/lwsmtp-server
  AUTOMATIC_MONITOR: true
  FILES: "*.au3 LICENSE" # seperate multiple entries with ,
  FILES_NEW: "*.au3 LICENSE*" # seperate multiple entries with ,
  EXTRA: mv LICENSE LICENSE_LWServer-SMTP # do an extra command like renaming
  USERNAME: ${{ github.actor }}
  ADDRESS_SUFFIX: users.noreply.github.com
  TOKEN_NAME: ACCESS_TOKEN # uncomment to use a secret with that name
  # SOURCE_BRANCH: source_alternate_branch # uncomment to takes files from a non default source branch
  # TARGET_BRANCH: target_alternate_branch # uncomment to monitor a non default target branch
  # TARGET_PATH: target_alternate_path # uncomment to monitor a non default target branch
  PATH_SOURCE_CHECKOUT: temp_folder
  THE_SECRET: ${{ secrets.TOKEN_NAME || 'default_value' }}

on: # Remove # below for non default branches
  workflow_dispatch:
  push:
#    branches:
#      - ${{ env.TARGET_BRANCH }}
#    paths:
#      - ${{ env.TARGET_PATH }}

jobs:
  pull-file:
    runs-on: ubuntu-latest
    steps:
      - name: Check whether to automatically monitor
        if: ${{ github.event_name != 'workflow_dispatch' && env.AUTOMATIC_MONITOR == false }}
        run: |
          exit 1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout source with token and branch
        if: env.THE_SECRET != 'default_value' && env.SOURCE_BRANCH
        uses: actions/checkout@v3
        with:
            repository: env.SOURCE_REPO
            ref: ${{ env.SOURCE_BRANCH }}
            token: ${{ secrets[env.TOKEN_NAME] }}
            path: env.PATH_SOURCE_CHECKOUT

      - name: Checkout source with token but without branch
        if: env.THE_SECRET != 'default_value' && !env.SOURCE_BRANCH
        uses: actions/checkout@v3
        with:
          repository: env.SOURCE_REPO
          token: ${{ secrets[env.TOKEN_NAME] }}
          path: env.PATH_SOURCE_CHECKOUT

      - name: Checkout source without token but with branch
        if: env.THE_SECRET == 'default_value' && env.SOURCE_BRANCH
        uses: actions/checkout@v3
        with:
          repository: env.SOURCE_REPO
          ref: ${{ env.SOURCE_BRANCH }}
          path: env.PATH_SOURCE_CHECKOUT

      - name: Checkout source without token and without branch
        if: env.THE_SECRET == 'default_value' && !env.SOURCE_BRANCH
        uses: actions/checkout@v3
        with:
            repository: env.SOURCE_REPO
            path: env.PATH_SOURCE_CHECKOUT

      - name: Update
        run: |
          cd source-repo
          $EXTRA
          cp -u $FILES_NEW ../
          cd ..

      - name: Commit
        run: |
          git config user.name "$USERNAME"
          git config user.email "$USERNAME@$ADDRESS_SUFFIX"
          git add $FILES_NEW
          git commit -m "Pulled files from $SOURCE_REPO."

      - name: Push
        run: |
          if [ -n "$TARGET_BRANCH" ]; then
            git push origin $TARGET_BRANCH
          else
            git push
          fi
