name: Pull File from Another Repository on Push
env:
  SOURCE_REPO: https://github.com/lwcorp/lwserver-smtp
  AUTOMATIC_MONITOR: true
  FILES: \*.au3,LICENSE # seperate multiple entries with ,
  FILES_NEW: \*.au3,LICENSE* # seperate multiple entries with ,
  EXTRA: mv LICENSE LICENSE_LWServer-SMTP # do an extra command like renaming
  # TOKEN_NAME: ACCESS_TOKEN # uncomment to use a secret with that name
  # SOURCE_BRANCH: source_alternate # uncomment to not monitor the default branch
  # TARGET_BRANCH: target_alternate # uncomment to not push to default branch

on: # Remove # below for non default branches
  workflow_dispatch:
#    inputs:
#      source_branch:
#        description: '${{ env.SOURCE_BRANCH }}'
#        required: false
  push:
#    branches:
#      - ${{ env.SOURCE_BRANCH }}
    paths:
      - ./source-repo/**

jobs:
  pull-file:
    runs-on: ubuntu-latest
    steps:
      - name: Check whether to automatically monitor
        if: ${{ github.event_name != 'workflow_dispatch' && env.AUTOMATIC_MONITOR == false }}
        run: |
          exit 1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull File
        run: |
          #!/bin/sh

          if [ -n "${{ env.TOKEN_NAME }}" ]; then
            REPO_URL=https://${{ secrets[env.TOKEN_NAME] }}@${{ env.SOURCE_REPO }}.git
          else
            REPO_URL=${{ env.SOURCE_REPO }}
          fi

          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ -n "${{ github.event.inputs.source_branch }}" ]; then
              git clone -b ${{ github.event.inputs.source_branch }} $REPO_URL ${{ env.SOURCE_REPO }}
            else
              git clone $REPO_URL ${{ env.SOURCE_REPO }}
            fi
          else
            git clone -b ${{ github.ref }} $REPO_URL ${{ env.SOURCE_REPO }}
          fi
          cp ${{ env.SOURCE_REPO }}/{${{ env.FILES }}} .
          ${{ env.EXTRA }}

      - name: Commit
        run: |
          git add ${{ env.FILES_NEW }}
          git commit -m "Pulled file from ${{ env.SOURCE_REPO }} and renamed."

      - name: Push
        run: |
          if [ -n "${{ env.TARGET_BRANCH }}" ]; then
            git push origin ${{ env.TARGET_BRANCH }}
          else
            git push
          fi
