name: Pull File from Another Repository on Push
secrets:
  SOURCE_REPO: https://github.com/example/source-repo
  AUTOMATIC_MONITOR # uncomment to not automatically monitor for pushes
  # TOKEN_NAME: ACCESS_TOKEN # uncomment to use a secret with that name
  # SOURCE_BRANCH: source_alternate # uncomment to not monitor the default branch
  # TARGET_BRANCH: target_alternate # uncomment to not push to default branch

on:
  workflow_dispatch:
    if: github.event.inputs.source_branch != ''
    inputs:
      source_branch:
        description: '${{ secrets.SOURCE_BRANCH }}'
        required: false
  push:
    if: github.event.inputs.source_branch != ''
    branches:
      - ${{ secrets.SOURCE_BRANCH }}
    paths:
      - ./source-repo/**

jobs:
  pull-file:
    runs-on: ubuntu-latest
    steps:
      - name: Check whether to automatically monitor
        if: ${{ github.event_name != 'workflow_dispatch' && secrets.AUTOMATIC_MONITOR == '' }}
        run: |
          exit 1

      - uses: actions/checkout@v3

      - name: Pull File
        uses: actions/github-script@v3
        with:
          script: |
            #!/bin/sh

            if [ -n "${{ secrets.TOKEN_NAME }}" ]; then
              REPO_URL=https://${{ secrets[secrets.TOKEN_NAME] }}@${{ secrets.SOURCE_REPO }}.git
            else
              REPO_URL=${{ secrets.SOURCE_REPO }}
            fi

            if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
              if [ -n "${{ github.event.inputs.source_branch }}" ]; then
                git clone -b ${{ github.event.inputs.source_branch }} $REPO_URL source-repo
              else
                git clone $REPO_URL source-repo
              fi
            else
              git clone -b ${{ github.ref }} $REPO_URL source-repo
            fi
            cp source-repo/file.txt .
            mv file.txt foobar.txt

      - name: Commit
        run: |
          git add foobar.txt
          git commit -m "Pulled file from ${{ secrets.SOURCE_REPO }} and renamed."

      - name: Push
        run: |
          if [ -n "${{ secrets.TARGET_BRANCH }}" ]; then
            git push origin ${{ secrets.TARGET_BRANCH }}
          else
            git push
          fi
